#!/bin/sh

case "${1}" in
    [vV]im)
        if ! mkdir -p ~/.vim/autoload/; then
            printf "Error: mkdir failed to create ${HOME}/.vim/autoload"
            exit 1
        fi
        if curl -fLo ~/.vim/autoload/plug.vim https://raw.github.com/junegunn/vim-plug/master/plug.vim; then
            printf "No internet connection '%s'" "$?"
        fi
        ln -s ~/.dotfiles/vim/.vimrc ~/.vimrc
        vim +PlugInstall +qall
        ;;
    [nN]vim)
        if ! mkdir -p ~/.config/nvim/autoload; then
            printf "Error: mkdir failed to create ${HOME}/.config/nvim/autoload"
            exit 1
        fi
        curl -fLo ~/.config/nvim/autoload/plug.vim https://raw.github.com/junegunn/vim-plug/master/plug.vim
        ln -s ~/.dotfiles/vim/.vimrc ~/.config/nvim/init.vim
        nvim +PlugInstall +qall
        ;;
    *)
        printf "%s [vim|nvim]" "${0}"
        ;;
esac
