#!/bin/bash
apps=(\
    sxhkd
    polybar
    )

for app in ${apps[@]}; do
    killall -q -e "${app}"
done

sxhkd &
polybar --reload default &

bspc monitor -d I II III IV V
bspc desktop -f '^1'

bspc config border_width 2
bspc config window_gap 10

bspc config split_ratio 0.50
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc config focus_follows_pointer true
bspc config initial_polarity second_child

bspc config normal_border_color '#928374'
bspc config focused_border_color '#cc241d'
bspc config presel_border_color '#d65d0e'

bspc rule -a 'chromium-browser' desktop='^2' follow=on
